using SuperRecruiter.Shared.Helpers;

namespace SuperRecruiter.Shared.Constants;

public record EuRealm(string Name, string Slug);

/// <summary>
/// Static list of EU realms, used to power the Discord realm autocomplete.
/// Needs a manual update when Blizzard adds or renames a realm.
/// </summary>
public static class EuRealms
{
    private static readonly string[] Names =
    [
        "Aegwynn",
        "Aerie Peak",
        "Agamaggan",
        "Aggra (Português)",
        "Aggramar",
        "Ahn'Qiraj",
        "Al'Akir",
        "Alexstrasza",
        "Alleria",
        "Alonsus",
        "Aman'Thul",
        "Ambossar",
        "Anachronos",
        "Anetheron",
        "Antonidas",
        "Anub'arak",
        "Arak-arahm",
        "Arathi",
        "Arathor",
        "Archimonde",
        "Argent Dawn",
        "Arygos",
        "Aszune",
        "Auchindoun",
        "Azjol-Nerub",
        "Azshara",
        "Azuremyst",
        "Baelgun",
        "Balnazzar",
        "Blackhand",
        "Blackmoore",
        "Blackrock",
        "Blackscar",
        "Blade's Edge",
        "Bladefist",
        "Bloodfeather",
        "Bloodhoof",
        "Bloodscalp",
        "Blutkessel",
        "Booty Bay",
        "Borean Tundra",
        "Boulderfist",
        "Bronze Dragonflight",
        "Bronzebeard",
        "Burning Blade",
        "Burning Legion",
        "Burning Steppes",
        "C'Thun",
        "Chamber of Aspects",
        "Chants éternels",
        "Cho'gall",
        "Chromaggus",
        "Colinas Pardas",
        "Confrérie du Thorium",
        "Conseil des Ombres",
        "Crushridge",
        "Culte de la Rive noire",
        "Daggerspine",
        "Dalaran",
        "Dalvengyr",
        "Darkmoon Faire",
        "Darksorrow",
        "Darkspear",
        "Das Konsortium",
        "Das Syndikat",
        "Deathwing",
        "Defias Brotherhood",
        "Dentarg",
        "Der Abyssische Rat",
        "Der Mithrilorden",
        "Der Rat von Dalaran",
        "Destromath",
        "Dethecus",
        "Deviate Delight",
        "Die Aldor",
        "Die Arguswacht",
        "Die Nachtwache",
        "Die Silberne Hand",
        "Die Todeskrallen",
        "Die ewige Wacht",
        "Doomhammer",
        "Draenor",
        "Dragonblight",
        "Dragonmaw",
        "Drak'thul",
        "Drek'Thar",
        "Dun Modr",
        "Dun Morogh",
        "Dunemaul",
        "Durotan",
        "Earthen Ring",
        "Echsenkessel",
        "Eitrigg",
        "Eldre'Thalas",
        "Elune",
        "Emerald Dream",
        "Emeriss",
        "Eonar",
        "Eredar",
        "Executus",
        "Exodar",
        "Festung der Stürme",
        "Forscherliga",
        "Frostmane",
        "Frostmourne",
        "Frostwhisper",
        "Frostwolf",
        "Garona",
        "Garrosh",
        "Genjuros",
        "Ghostlands",
        "Gilneas",
        "Gorgonnash",
        "Grim Batol",
        "Gul'dan",
        "Hakkar",
        "Haomarush",
        "Hellfire",
        "Hellscream",
        "Hyjal",
        "Illidan",
        "Jaedenar",
        "Kael'thas",
        "Karazhan",
        "Kargath",
        "Kazzak",
        "Kel'Thuzad",
        "Khadgar",
        "Khaz Modan",
        "Khaz'goroth",
        "Kil'jaeden",
        "Kilrogg",
        "Kirin Tor",
        "Kor'gall",
        "Krag'jin",
        "Krasus",
        "Kul Tiras",
        "Kult der Verdammten",
        "La Croisade écarlate",
        "Laughing Skull",
        "Les Clairvoyants",
        "Les Sentinelles",
        "Lightbringer",
        "Lightning's Blade",
        "Lordaeron",
        "Los Errantes",
        "Lothar",
        "Madmortem",
        "Magtheridon",
        "Mal'Ganis",
        "Malfurion",
        "Malorne",
        "Malygos",
        "Mannoroth",
        "Marécage de Zangar",
        "Mazrigos",
        "Medivh",
        "Minahonda",
        "Moonglade",
        "Mug'thol",
        "Nagrand",
        "Nathrezim",
        "Naxxramas",
        "Nazjatar",
        "Nefarian",
        "Nemesis",
        "Neptulon",
        "Ner'zhul",
        "Nera'thor",
        "Nethersturm",
        "Nordrassil",
        "Norgannon",
        "Nozdormu",
        "Onyxia",
        "Outland",
        "Perenolde",
        "Pozzo dell'Eternità",
        "Quel'Thalas",
        "Ragnaros",
        "Rajaxx",
        "Rashgarroth",
        "Ravencrest",
        "Ravenholdt",
        "Razuvious",
        "Rexxar",
        "Runetotem",
        "Sanguino",
        "Sargeras",
        "Saurfang",
        "Scarshield Legion",
        "Sen'jin",
        "Shadowsong",
        "Shattered Halls",
        "Shattered Hand",
        "Shen'dralar",
        "Silvermoon",
        "Sinstralis",
        "Skullcrusher",
        "Spinebreaker",
        "Sporeggar",
        "Steamwheedle Cartel",
        "Stormrage",
        "Stormreaver",
        "Stormscale",
        "Sunstrider",
        "Suramar",
        "Sylvanas",
        "Taerar",
        "Talnivarr",
        "Tarren Mill",
        "Teldrassil",
        "Templenoir",
        "Terenas",
        "Terokkar",
        "Terrordar",
        "The Maelstrom",
        "The Sha'tar",
        "The Venture Co",
        "Theradras",
        "Thermaplugg",
        "Thrall",
        "Throk'Feroth",
        "Thunderhorn",
        "Tichondrius",
        "Tirion",
        "Todeswache",
        "Trollbane",
        "Turalyon",
        "Twilight's Hammer",
        "Twisting Nether",
        "Tyrande",
        "Uldaman",
        "Ulduar",
        "Uldum",
        "Un'Goro",
        "Varimathras",
        "Vashj",
        "Vek'lor",
        "Vek'nilash",
        "Vol'jin",
        "Wildhammer",
        "Wrathbringer",
        "Xavius",
        "Ysera",
        "Ysondre",
        "Zenedar",
        "Zirkel des Cenarius",
        "Zul'jin",
        "Zuluhed",
    ];

    public static readonly IReadOnlyList<EuRealm> All = [.. Names.Select(name => new EuRealm(name, RealmSlugHelper.ToSlug(name)))];

    private static readonly Dictionary<string, EuRealm> BySlug = All.ToDictionary(realm => realm.Slug, StringComparer.OrdinalIgnoreCase);

    /// <summary>
    /// Resolves a realm from either its display name or its slug.
    /// </summary>
    public static EuRealm? Find(string nameOrSlug)
    {
        if (string.IsNullOrWhiteSpace(nameOrSlug))
            return null;

        return BySlug.TryGetValue(RealmSlugHelper.ToSlug(nameOrSlug), out var realm) ? realm : null;
    }

    /// <summary>
    /// Returns realms matching the search term, prefix matches first. Discord allows at most 25 autocomplete choices.
    /// </summary>
    public static IReadOnlyList<EuRealm> Search(string? term, int max = 25)
    {
        if (string.IsNullOrWhiteSpace(term))
            return [.. All.Take(max)];

        var normalized = RealmSlugHelper.ToSlug(term);

        return
        [
            .. All.Where(realm => realm.Slug.Contains(normalized, StringComparison.Ordinal))
                .OrderByDescending(realm => realm.Slug.StartsWith(normalized, StringComparison.Ordinal))
                .ThenBy(realm => realm.Name, StringComparer.OrdinalIgnoreCase)
                .Take(max),
        ];
    }
}
